import { ImageWithFallback } from "../figma/ImageWithFallback";
import { Button } from "../ui/button";
import { Sparkles, Map, Users, Shield, Star, Plane, Leaf, LucideIcon } from "lucide-react";
import { Card, CardContent } from "../ui/card";
import { motion } from "motion/react";

interface LandingPageProps {
  onNavigate: (page: string) => void;
}

// Reusable component to handle the specific icon styling logic
const FeatureIcon = ({ Icon, index }: { Icon: LucideIcon, index: number }) => {
  const primaryColor = "#F7A160"; // Orange/Brown - Target for Tailwind configuration
  const secondaryColor = "#F7DC79"; // Yellow/Gold - Target for Tailwind configuration

  const color = index % 2 === 0 ? primaryColor : secondaryColor;

  return (
    <div
      className="w-12 h-12 rounded-lg flex items-center justify-center mb-4"
      // We keep the background style inline for now, but apply opacity to the div
      style={{ backgroundColor: color, opacity: 0.2 }}
    >
      {/* Icon itself remains fully opaque */}
      <Icon className="w-6 h-6 opacity-100" style={{ color: color }} />
    </div>
  );
};

export function LandingPage({ onNavigate }: LandingPageProps) {
  const features = [
    {
      icon: Sparkles,
      title: "AI-Powered Planning",
      description: "Get personalized itineraries generated by advanced AI based on your preferences",
    },
    {
      icon: Users,
      title: "Expert Local Guides",
      description: "Connect with verified guides who know the area and speak your language",
    },
    {
      icon: Shield,
      title: "QR Verification",
      description: "Scan your guide's QR code for secure identity verification on arrival",
    },
    {
      icon: Star,
      title: "Trusted Reviews",
      description: "Read authentic reviews with photos from real travelers",
    },
  ];

  return (
    <div className="min-h-screen" style={{ backgroundColor: "#fefcf8" }}>
      {/* Hero Section */}
      <section className="relative overflow-hidden">
        <div className="absolute inset-0 z-0">
          <ImageWithFallback
            src="https://images.unsplash.com/photo-1668674789524-ad360545aef3?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxzcmklMjBsYW5rYSUyMGJlYWNoJTIwbGFuZHNjYXBlfGVufDF8fHx8MTc2MDc4MzM0OXww&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral"
            alt="Sri Lankan beach landscape"
            className="w-full h-full object-cover opacity-20"
          />
        </div>
        
        <div className="relative z-10 w-full px-4 sm:px-6 lg:px-8 py-32">
          <div className="max-w-3xl">
            <motion.h1 
              className="text-6xl mb-6" 
              style={{ color: "#F7A160" }}
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.6 }}
            >
              Plan Your Perfect Trip with AI
            </motion.h1>
            <motion.p 
              className="text-2xl text-gray-600 mb-8"
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.6, delay: 0.2 }}
            >
              Experience personalized travel planning powered by AI. Connect with expert local guides and create unforgettable memories.
            </motion.p>
            <motion.div
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.6, delay: 0.4 }}
            >
              <Button
                size="lg"
                className="text-lg px-8 py-6"
                style={{ backgroundColor: "#F7A160" }}
                onClick={() => onNavigate("planner")}
              >
                <Plane className="mr-2 w-5 h-5" />
                Plan Trip with AI
              </Button>
            </motion.div>
          </div>
        </div>
      </section>

      {/* Features Section */}
      <section className="py-24 bg-white">
        <div className="w-full px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-16">
            <h2 className="text-4xl mb-4" style={{ color: "#F7A160" }}>
              How It Works
            </h2>
            <p className="text-xl text-gray-600">
              Your journey from planning to memories in simple steps
            </p>
          </div>

          {/* FIXED: Changed lg:grid-cols-5 to lg:grid-cols-4 for 4 features */}
          <div className="grid md:grid-cols-2 lg:grid-cols-4 gap-8">
            {features.map((feature, index) => {
              const Icon = feature.icon;
              return (
                <motion.div
                  key={index}
                  initial={{ opacity: 0, y: 20 }}
                  whileInView={{ opacity: 1, y: 0 }}
                  transition={{ duration: 0.5, delay: index * 0.1 }}
                  viewport={{ once: true }}
                  className="h-full"
                >
                  <Card className="border-none shadow-lg hover:shadow-xl transition-all bg-white h-full">
                    <CardContent className="p-6 flex flex-col h-full">
                      {/* REFACTORED: Use the dedicated FeatureIcon component */}
                      <FeatureIcon Icon={Icon} index={index} />
                      <h3 className="text-xl mb-2">{feature.title}</h3>
                      <p className="text-gray-600 flex-1">{feature.description}</p>
                    </CardContent>
                  </Card>
                </motion.div>
              );
            })}
          </div>
        </div>
      </section>

      {/* CTA Section */}
      <section className="py-24">
        <div className="w-full px-4 sm:px-6 lg:px-8 text-center">
          <motion.div
            className="rounded-2xl p-16 shadow-xl"
            style={{ backgroundColor: "#F7A160" }}
            initial={{ opacity: 0, scale: 0.95 }}
            whileInView={{ opacity: 1, scale: 1 }}
            transition={{ duration: 0.6 }}
            viewport={{ once: true }}
          >
            <h2 className="text-4xl mb-4 text-white">
              Ready to Start Your Adventure?
            </h2>
            <p className="text-xl text-white mb-8 opacity-90">
              Join thousands of travelers who trust SeranGo for sustainable journeys
            </p>
            <Button
              size="lg"
              variant="secondary"
              className="text-lg px-8 py-6"
              onClick={() => onNavigate("planner")}
            >
              Get Started Now
            </Button>
          </motion.div>
        </div>
      </section>
    </div>
  );
}